force-app/main/default/objects/EC_Invoice__c/EC_Invoice__c.object-meta.xml
<CustomObject>
    <description>Invoice</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Amount__c.field-meta.xml
<CustomField>
    <fullName>EC_Amount__c</fullName>
    <description>Amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>EC_Invoice_Date__c</fullName>
    <description>Invoice Date</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EC_Opportunity__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Status__c.field-meta.xml
<CustomField>
    <fullName>EC_Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EC_OpportunityTriggerHandler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-08-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class EC_OpportunityTriggerHandler {

        /**
        * @description 
        * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
        * @param newList 
        **/
        public static void beforeInsert(List<Opportunity> newList){
            updateCloseDate(newList,null);
        }
        
        /**
        * @description 
        * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
        * @param newList 
        * @param oldMap 
        **/
        public static void beforeUpdate(List<Opportunity> newList, Map<Id,Opportunity> oldMap){
            updateCloseDate(newList,oldMap);
        }
        /**
        * @description 
        * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
        * @param newList 
        **/
        public static void afterInsert(List<Opportunity> newList){
            createInvoice(newList,null);
        }
    
    	/**
    	* @description 
    	* @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
    	* @param newList 
    	* @param oldMap 
    	**/
    	public static void afterUpdate(List<Opportunity> newList, Map<Id,Opportunity> oldMap){
            createInvoice(newList,oldMap);
        }

        /**
        * @description 
        * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
        * @param newList 
        * @param oldMap 
        **/
        public static void updateCloseDate(List<Opportunity> newList, Map<Id,Opportunity> oldMap){
            try{
                for(Opportunity oppObj : newList){
                    if( ( oppObj.StageName == EC_Constants.closedWonStatus || oppObj.StageName == EC_Constants.closedLostStatus ) && ( ( oldMap == null ) || ( oldMap !=  null && oldMap.get(oppObj.Id).StageName != oppObj.StageName  ) ) ){
                        oppObj.CloseDate = Date.today();
                    }
                }
            }catch(Exception ex){
                throw new EC_Exception(ex.getMessage());
            }
        }
    
    
    	/**
    	* @description 
    	* @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
    	* @param newList 
    	* @param oldMap 
    	**/
        public static void createInvoice(List<Opportunity> newList, Map<Id,Opportunity> oldMap){
            try{
                List<EC_Invoice__c> invoiceList = new List<EC_Invoice__c>();
                for(Opportunity oppObj : newList){
                    if( (oppObj.StageName == EC_Constants.closedWonStatus && oppObj?.Amount > 0) && ( ( oldMap == null ) || ( oldMap !=  null && oldMap.get(oppObj.Id).StageName != oppObj.StageName  ) ) ){
                        EC_Invoice__c tempInvoice = new EC_Invoice__c();
                        tempInvoice.Name = EC_Constants.deliveryMilestone;
                        tempInvoice.EC_Amount__c = oppObj?.Amount * 0.4;
                        tempInvoice.EC_Invoice_Date__c = Date.today();
                        tempInvoice.EC_Opportunity__c = oppObj.Id;
                        tempInvoice.EC_Status__c = EC_Constants.openStatus;
                        invoiceList.add(tempInvoice);
                    }
                }
            insert invoiceList;
            }catch(Exception ex){
                throw new EC_Exception(ex.getMessage());
            }
        }
}