force-app/main/default/objects/EC_Invoice__c/EC_Invoice__c.object-meta.xml
<CustomObject>
    <description>Invoice</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Amount__c.field-meta.xml
<CustomField>
    <fullName>EC_Amount__c</fullName>
    <description>Amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>EC_Invoice_Date__c</fullName>
    <description>Invoice Date</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>EC_Opportunity__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EC_Invoice__c/fields/EC_Status__c.field-meta.xml
<CustomField>
    <fullName>EC_Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EC_Invoiced_Amount__c.field-meta.xml
<CustomField>
    <fullName>EC_Invoiced_Amount__c</fullName>
    <description>Invoiced Amount</description>
    <label>Invoiced Amount</label>
    <summarizedField>EC_Invoice__c.EC_Amount__c</summarizedField>
    <summaryForeignKey>EC_Invoice__c.EC_Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EC_Remaning_Amount__c.field-meta.xml
<CustomField>
    <fullName>EC_Remaning_Amount__c</fullName>
    <formula>Amount -  EC_Invoiced_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaning Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EC_CreateOpportuniyInvoiceBatch.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-08-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class EC_CreateOpportuniyInvoiceBatch implements Database.Batchable<sobject>, Schedulable {
    
    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
    * @param bc 
    * @return Database.Querylocator 
    **/
    public Database.Querylocator start (Database.BatchableContext bc)
    {
        String query = 'SELECT Id, Amount, StageName, EC_Invoiced_Amount__c, (SELECT Id, Name, EC_Invoice_Date__c, EC_Opportunity__c FROM Invoices__r ORDER BY EC_Invoice_Date__c DESC LIMIT 1) FROM Opportunity WHERE StageName = \'Closed Won\' AND EC_Remaning_Amount__c > 0 WITH SECURITY_ENFORCED';
        return Database.getQueryLocator(query);
    }
    
    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
    * @param bc 
    * @param opportunityList 
    **/
    public void execute(Database.BatchableContext bc, List<Opportunity> opportunityList){
        try{
            List<EC_Invoice__c> invoiceList = new List<EC_Invoice__c>();
            for(Opportunity oppObj : opportunityList){
                if(oppObj.Invoices__r.isEmpty()){
                    continue;
                }else if(oppObj.Invoices__r[0].EC_Invoice_Date__c.addMonths(1) > Date.today()){
                    continue;                
                }
                String invoiceName = oppObj.Invoices__r[0].Name;
                String tempInvoiceNameCount;
                if (invoiceName.contains(EC_Constants.subscriptionMilestone)) {
                    tempInvoiceNameCount = String.valueOf(Integer.valueOf(invoiceName.replace(EC_Constants.subscriptionMilestone, '')) + 1 );
                } else {
                    tempInvoiceNameCount = '1'; 
                }
                EC_Invoice__c tempInvoice = new EC_Invoice__c();
                tempInvoice.Name = EC_Constants.subscriptionMilestone+tempInvoiceNameCount;
                tempInvoice.EC_Amount__c = (oppObj.Amount * 0.6) / 12;
                tempInvoice.EC_Invoice_Date__c = Date.today();
                tempInvoice.EC_Opportunity__c = oppObj.Id;
                tempInvoice.EC_Status__c = EC_Constants.openStatus;
                invoiceList.add(tempInvoice);
            }
            insert invoiceList;
        }catch(Exception ex){
            throw new EC_Exception(ex.getMessage());
        }
    }
    
    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
    * @param bc 
    **/
    public void finish (Database.BatchableContext bc)
    {

    }

    
    /**
    * @description 
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 02-08-2025 
    * @param sc 
    **/
    public void execute(SchedulableContext sc){
        EC_CreateOpportuniyInvoiceBatch batchObj = new EC_CreateOpportuniyInvoiceBatch();
        database.executebatch(batchObj, 200);
    }  

}